"""Generate a C array embedding the INT8 TFLite model for firmware use.

Usage:
    python -m ml.quantization.generate_model_cc --int8-model ml/artifacts/small_cnn_best_int8.tflite

Writes:
    firmware/esp32s3/components/kws_inference/model/kws_model_data.cc
    firmware/esp32s3/components/kws_inference/model/kws_model_data.h

This replaces the placeholder model array that ships in the repo (built
from an untrained model, size 0) with the team's real trained model.
"""
from __future__ import annotations

import argparse
import datetime
from pathlib import Path

HEADER_TEMPLATE = """\
// AUTO-GENERATED by ml/quantization/generate_model_cc.py
// Source: {source_model}
// Generated: {timestamp}
// DO NOT EDIT BY HAND - regenerate from the .tflite file instead.

#ifndef KWS_MODEL_DATA_H_
#define KWS_MODEL_DATA_H_

#include <cstdint>

extern const unsigned char g_kws_model_data[];
extern const unsigned int g_kws_model_data_len;

#endif  // KWS_MODEL_DATA_H_
"""

SOURCE_TEMPLATE = """\
// AUTO-GENERATED by ml/quantization/generate_model_cc.py
// Source: {source_model}
// Generated: {timestamp}
// Model size: {size_bytes} bytes
// DO NOT EDIT BY HAND - regenerate from the .tflite file instead.

#include "kws_model_data.h"

alignas(16) const unsigned char g_kws_model_data[] = {{
{byte_array}
}};

const unsigned int g_kws_model_data_len = {size_bytes};
"""


def bytes_to_c_array(data: bytes, bytes_per_line: int = 12) -> str:
    lines = []
    for i in range(0, len(data), bytes_per_line):
        chunk = data[i:i + bytes_per_line]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--int8-model", type=Path, required=True)
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("firmware/esp32s3/components/kws_inference/model"),
    )
    args = parser.parse_args(argv)

    if not args.int8_model.exists():
        print(f"[ERROR] Model not found: {args.int8_model}. Run ml/quantization/convert_int8.py first.")
        return 2

    data = args.int8_model.read_bytes()
    if len(data) == 0:
        print("[ERROR] Model file is empty.")
        return 1

    timestamp = datetime.datetime.utcnow().isoformat() + "Z"
    args.output_dir.mkdir(parents=True, exist_ok=True)

    header_path = args.output_dir / "kws_model_data.h"
    header_path.write_text(
        HEADER_TEMPLATE.format(source_model=args.int8_model, timestamp=timestamp)
    )

    source_path = args.output_dir / "kws_model_data.cc"
    source_path.write_text(
        SOURCE_TEMPLATE.format(
            source_model=args.int8_model,
            timestamp=timestamp,
            size_bytes=len(data),
            byte_array=bytes_to_c_array(data),
        )
    )

    print(f"Wrote {header_path}")
    print(f"Wrote {source_path} ({len(data):,} bytes embedded)")
    print(
        "Next: rebuild the firmware (scripts/build_firmware.sh) and re-measure "
        "Flash/RAM usage on the actual ESP32-S3 board."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
