// AUTO-GENERATED by ml/quantization/generate_model_cc.py
// Source: ml\artifacts\ds_cnn_final_int8.tflite
// Generated: 2026-09-03T13:28:01.330709Z
// DO NOT EDIT BY HAND - regenerate from the .tflite file instead.

#ifndef KWS_MODEL_DATA_H_
#define KWS_MODEL_DATA_H_

#include <cstdint>

extern const unsigned char g_kws_model_data[];
extern const unsigned int g_kws_model_data_len;

#endif  // KWS_MODEL_DATA_H_
